language: bash

services:
  - docker

env:
  global:
    - RUBY25=2.5.1
    - RUBY24=2.4.4
    - RUBY23=2.3.7
  matrix:
    - RUBY_VER="${RUBY25}" TAGS=2.5,2,latest
    - RUBY_VER="${RUBY24}" TAGS=2.4
    - RUBY_VER="${RUBY23}" TAGS=2.3
    - RUBY_VER="${RUBY25}" RUBY_DEV=1 TAGS=2.5-dev,2-dev
    - RUBY_VER="${RUBY24}" RUBY_DEV=1 TAGS=2.4-dev
    - RUBY_VER="${RUBY23}" RUBY_DEV=1 TAGS=2.3-dev
    - RUBY_VER="${RUBY25}" RUBY_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=2.5-dev-macos,2-dev-macos
    - RUBY_VER="${RUBY24}" RUBY_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=2.4-dev-macos
    - RUBY_VER="${RUBY23}" RUBY_DEV=1 WODBY_USER_ID=501 WODBY_GROUP_ID=20 TAGS=2.3-dev-macos
    - RUBY_VER="${RUBY25}" RUBY_PURE=1 TAGS=2.5,2-pure
    - RUBY_VER="${RUBY24}" RUBY_PURE=1 TAGS=2.4-pure
    - RUBY_VER="${RUBY23}" RUBY_PURE=1 TAGS=2.3-pure

script:
  - set -e
  - travis_retry make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
